### ISSUE TITLE
Stutter on FadeInDown Animation

### ISSUE THREAD

**Issue by alimhaq** [Klerith/animate_do_package#1]
Hi, I'm noticing when I use the fade in down animation stutters around 500ms into the animation (when the duration is 1000ms). The current way I'm getting around it is to have the delay set at 550ms and then starting the animation, this seems to avoid the stutter, but ideally I would have the animation load as soon as possible. The stutter is reproducible 100% on my production and debug builds on Flutter 1.20. Would it be possible to fix this?

**Comment by Klerith** [comment]
Hi @alimhaq 
Do you think is possible create a small example of the issue so I can work it out and fix it?

A github repo would be nice.
