### ISSUE TITLE
FadeOuts not working

### ISSUE THREAD

**Issue by guplem** [Klerith/animate_do_package#12]
I am trying to fade out a button if I don't have to show it.

Am I doing something wrong? 

This is the code: 
```
GetBuilder<SessionController>(builder: (sessionController) {

  if (widget.plan.participantsIds.contains(sessionController.loggedUserId)) {
    print("IN");
    return FadeIn(
      duration: kThemeAnimationDuration * 2,
      child: Bounce (
        child: ChatButton(plan: widget.plan),
        duration: kThemeAnimationDuration * 4.5,

      ),
    );
  } else if (!widget.plan.participantsIds.contains(sessionController.loggedUserId)) {
    print("OUT");

    return ZoomOut(
      child: ChatButton(plan: widget.plan),
    );
    //
  }

  print("ERROR");
  return const SizedBox.shrink();

})
```

I am using [Get ](https://pub.dev/packages/get) for state management. 

The FadeIn works, and changing the FadeOut for ZoomOut works too, however, any of the FadeOuts seems to work.
The prints work as expected.

**Comment by GusOEther** [comment]
FadeOuts not working on Android here too. (animate_do v2.0.0)
ZoomOut work though.

**Comment by afijal** [comment]
chek animate property

**Comment by GusOEther** [comment]
What do you like to tell us?
As I said, everything from animate_do works except ZoomOuts.
At least on Android API 31.

**Comment by mosayeb-masoumi** [comment]
FadeOuts not working

**Comment by Klerith** [comment]
You are right, I will fix this in the next release, working on that version now.
