### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by halimpuckjava** [Klerith/animate_do_package#14]
hi

1.  add property 'to' to distinct between from & to (issue when use zoom effect, i prefer from=initZoom to=finalZoom)

2. apply animations in parallel (ex: fade + zoom + ... )

3. handle animations events (begin, end, pause, resume)

**Comment by Klerith** [comment]
Thank you @halimpuckjava probably I could add listeners

**Comment by Klerith** [comment]
1. I fix some bugs in the ZoomIn and ZoomOut widgets to close this issue.
2. Now it is possible to apply an animation widget inside another one; just keep an eye on the timings; for example, if the ZoomIn takes 0.5 seconds and the fadeIn takes 0.5 seconds, you will barely see the ZoomIn
3.  I added an "onFinish" property, which returns when the animation finishes going forwards or backwards
