### ISSUE TITLE
 i need exmple of AnimatedController ;

### ISSUE THREAD

**Issue by biloo-dev** [Klerith/animate_do_package#15]
**When you press the add to cart button, then The cart icon is animated**

![2022-03-31_235733](https://user-images.githubusercontent.com/37638323/161163444-2f5c734c-045b-41ba-ae26-71d04e9dcbc3.png)

**Comment by biloo-dev** [comment]
i have change this in your code .
it's worked for me,
can you fixed it please 
![2022-04-01_193201](https://user-images.githubusercontent.com/37638323/161322661-4d0f0375-de96-4a92-86e3-42e328bc9d1d.png)

**Comment by Klerith** [comment]
Sure, this is the example with the controller, I added on the example folder, but it will be there until next release, but you can find it now here

https://github.com/Klerith/animate_do_package/blob/master/example/controller-example.dart
