### ISSUE TITLE
Manual Trigger has no effect

### ISSUE THREAD

**Issue by alejandrogiubel** [Klerith/animate_do_package#17]
Set manual trigger to true has no effect. The widget keep doing the animation on load.

**Comment by junko2013** [comment]
+1

**Comment by Klerith** [comment]
Fixed, and also check the new property "animate", which you can use to trigger the animation forwards or backwards with only a boolean property, that can be changed with a StatefulWidget or a state manager.

**Comment by Klerith** [comment]
The manual trigger will be fixed in the next release that I have plans to release today + other fixes.

v3.1.0+
