### ISSUE TITLE
AnimationController methods should not be used after calling dispose.

### ISSUE THREAD

**Issue by kw2019ltd** [Klerith/animate_do_package#2]
Hi
getting below when iam jumping between tab ,

i have 3 tabs,  second tab has  FadeInUp(child:widget) 

now iam in tab 1 and iam moving to tab 3 getting below in logs

E/flutter (24189): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 456 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()
E/flutter (24189): AnimationController methods should not be used after calling dispose.
E/flutter (24189): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (24189): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (24189): #2      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:456:7)
E/flutter (24189): #3      _FadeInUpState.initState.<anonymous closure> (package:animate_do/animate_do.dart:283:54)
E/flutter (24189): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
E/flutter (24189): #5      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (24189): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24189): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (24189): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (24189): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (24189): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24189): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (24189): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (24189): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (24189): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (24189): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (24189): 
E/flutter (24189): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 456 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()
E/flutter (24189): AnimationController methods should not be used after calling dispose.
E/flutter (24189): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (24189): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (24189): #2      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:456:7)
E/flutter (24189): #3      _FadeInUpState.initState.<anonymous closure> (package:animate_do/animate_do.dart:283:54)
E/flutter (24189): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
E/flutter (24189): #5      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (24189): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24189): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (24189): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (24189): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (24189): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24189): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (24189): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (24189): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (24189): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (24189): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (24189): 
W/IInputConnectionWrapper(24189): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(24189): getTextBeforeCursor on inactive InputConnection

**Comment by FreddyKaiser** [comment]
Same for me, it may be related to the use of `delay:`

E/flutter (30776): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 741 pos 7: '_ticker != null': AnimationController.stop() called after AnimationController.dispose()
E/flutter (30776): AnimationController methods should not be used after calling dispose.
E/flutter (30776): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (30776): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (30776): #2      AnimationController.stop (package:flutter/src/animation/animation_controller.dart:741:7)
E/flutter (30776): #3      AnimationController.repeat (package:flutter/src/animation/animation_controller.dart:637:5)
E/flutter (30776): #4      _PulseState.initState.<anonymous closure> (package:animate_do/animate_do.dart:1985:40)
E/flutter (30776): #5      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
E/flutter (30776): #6      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (30776): #7      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (30776): #8      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (30776): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (30776): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (30776): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (30776): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (30776): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (30776): #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (30776): #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (30776): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by Klerith** [comment]
Thank you, I'll look into that and add some fail safe mechanism to prevent that.

**Comment by Klerith** [comment]
Hi, this is going to be fixed in the next update 1.7.4

**Comment by FreddyKaiser** [comment]
Tested and all fine now with 1.7.5, thanks

**Comment by frank-francisco** [comment]
The issue still exists when animate_do is used inside Pageview, looks like it's disposed onPageChanded. Any ideas or workaround?
