### ISSUE TITLE
Bug en v3.0.2 

### ISSUE THREAD

**Issue by eliasbest07** [Klerith/animate_do_package#23]
Felicidades Fernando por tan buen trabajo desarrollando y manteniendo este paquete. Encontré un bug en la versión más reciente porque yo lo había usado en la versión 2.1.0 y me funciona bastante bien, le doy un uso muy simple, para mostrar un Container y ocultarlo usando FadeInUpBig, cree un late AnimationController y lo asigno al controlador del widget FadeInUpBig, lo que me sucedió fue que cuando hacia click en un TextFormField dentro del Container que animo, la animación se restauraba cuando aparece el teclado en pantalla, como te digo este bug me aparece en la versión 3.0.2 porque lo baje a la versión 2.1.0 y este problema no aparece, pensé que era el gestor de estado por lo que intente con un StatefullWidget y el mismo bug, intente con riverpod y con getX, hasta que si me percate que bajando la versión del paquete me funciono como debería, digo que se restaura la animación porque si el parametro del widget FadeInUpBig animate esta en true, se inicia la animacion cuando aparece el teclado, y si animate esta en false la animación se ve en reversa 

![8d2e9935-c8bb-4ee2-b9d2-4cbd276c496d](https://user-images.githubusercontent.com/26911843/216842648-9d0c0408-2b41-438f-9afc-29b70957cd0f.jpeg)

![5d74b9a7-1a35-4e7b-9d7d-33488e612fa5](https://user-images.githubusercontent.com/26911843/216842668-10cbb00c-b83d-442b-9a5d-69c9a2a4c8e2.jpeg)

![a04ebbe7-e3d8-489c-955b-884e38310add](https://user-images.githubusercontent.com/26911843/216842674-813b6401-235f-4f53-9f0c-1ee51b9d69a7.jpeg)

![d74d1e0b-419e-42ec-9dca-478994923882](https://user-images.githubusercontent.com/26911843/216842681-50b094f3-650c-48be-b7f7-40a0fa54ac73.jpeg)

![a7c46baa-98cc-41ce-aa83-bdc8f0f1cff9](https://user-images.githubusercontent.com/26911843/216842686-63d32593-d7d1-411b-9dd8-d31b40330362.jpeg)

**Comment by egoan82** [comment]
Tengo el mismo inconveniente, has solucionado el problema?

**Comment by Klerith** [comment]
Estoy revisando ese feature, pero ya no tienen que usar el controlador para repetir o revertir la animación, añadí una propiedad llamada: "animate" en la cual con sólo poner un true o false, o cambiarle en tiempo de ejecución, se encarga de animar o revertir la animación sin necesidad del controlador.

Pero estoy revisando el controlador, porque ese feature debería de seguir funcionando.

**Comment by Klerith** [comment]
Ya encontré el problema, la solución la estoy aplicando en todos los widgets de animaciones.

Pero es importante que si usarán el controlador para controlar la animación, usen la property "manualTrigger" en TRUE, para que la animación no suceda a menos que usen el controlador expuesto.

Pero mi recomendación es que para este caso, usen la property: "animate" en TRUE o FALSE. Es mucho más fácil que tomar el controlador y animarlo.
