### ISSUE TITLE
FadeOut animation doesn't work on last update

### ISSUE THREAD

**Issue by spalut** [Klerith/animate_do_package#26]
Hi.
FadeOut animation stopped working after the last update. I have tried some of the other animations and they works as expected, but none of the FadeOut animations do

**Comment by spalut** [comment]
Hi.
Today I had time to do some tests. I found that the bool  animate is set on false on all FadeOut animations. When set to true, the animation works.

**Comment by Klerith** [comment]
Working correctly on v3.2.0, feel free to re-open the issue or create a new one if needed
