### ISSUE TITLE
No se oculta el icono al usar el ZoomOut

### ISSUE THREAD

**Issue by eivanphils** [Klerith/animate_do_package#34]
Buenas tardes al aplicarse la animación del zoomOut no desaparece el icono usado o puede ser que lo estoy usando mal, estoy trabajando con la version   animate_do: ^3.3.3

Adjunto el ejemplo del código implementando

```
 ZoomOut(
            from: 30,
            animate: activeAnimation,
            duration: const Duration(seconds: 1),
            child: const FaIcon(
              FontAwesomeIcons.twitter,
              size: 40,
              color: Colors.white,
            )),
      )

```
Adjunto imagen de como se ve

![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-19 at 19 50 33](https://github.com/Klerith/animate_do_package/assets/1909869/e9693d53-736f-4c47-9fbc-6d2a74b9a377)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-19 at 19 50 35](https://github.com/Klerith/animate_do_package/assets/1909869/fde68319-dfcf-4071-8d4b-679693070fcc)

**Comment by Klerith** [comment]
Ohh... creo que sé por qué paso...

Gracias por reportarlo, es que hice una restructuración de todo el código, estará resuelto en la versión 3.3.4

**Comment by Klerith** [comment]
Esto ya está resuelto en la versión 3.3.4 que acabo de publicar, si no te funciona actualizando el paquete, vuelve a abrir este issue por favor @eivanphils

**Comment by eivanphils** [comment]
@Klerith  pude validar con la version 3.3.4 y funciona perfecto, gracias
