### ISSUE TITLE
How to simulate SlideOutRight

### ISSUE THREAD

**Issue by martinlaregina** [Klerith/animate_do_package#4]
Hi,

I want to make like "SlideInRight" effect to show some widget, something like "SlideOutRight" to hide same widget.

There are a way to do that ?

Thanks a lot.

**Comment by Klerith** [comment]
You can do it, you can add the widget you want to animate into SlideInRight  and that one into SlideOutRight, but the SlideOutRight must have the property animate: false, then when you want to trigger the slideOut effect, you should change that animate property to true

```
 body: Center(
        child: ZoomOut(
          from: 0.5,
          animate: false, // true => you can use a state management in here
          child: ZoomIn(
            child: SquareWidget()
          )
        )
```
