### ISSUE TITLE
No smooth animation (emulator and smartphone)

### ISSUE THREAD

**Issue by gipic** [Klerith/animate_do_package#5]
I don't know if it's just me but both on android emulator and on smartphone (galaxy s7), animations are not smooth.
This is just about testing (so fix with deployment) or is a problem?

**Comment by Klerith** [comment]
Hi... Well, I have tested it on numerous devices and seems to be working great... are you experimenting frame drops? if so, in which animations?

**Comment by augusto3691** [comment]
you ll never get a smooth FPS on development mode, try build a release mode of flutter app to get a smooth animation

**Comment by Klerith** [comment]
The animations are not as smooth on the emulator, mostly because the emulator itself is not as smooth as the real device, just try it on your phone :)
