### ISSUE TITLE
FadeOut animations don't work (with solution) - Infinite property not working unless I use delay

### ISSUE THREAD

**Issue by gipic** [Klerith/animate_do_package#6]
How can I use FadeOut animations? FadeIn works correctly.
I am trying to replace FadeIn with FadeOut just for fun but with FadeOut anything happens with Square container (like the example).

Example:

```
...
FadeOut(
 child: Square(),
),
...
```

Emulator: Pixel 4 XL API 29

EDIT: Also animations that support infinite property don't animate in loop (infinite: true) unless I add the delay property. Bug?

UPDATE: FadeOut animations work if I set "animate" property to true.

```
...
FadeOutRightBig(
 child: Square(),
 animate: true,
),
...
```

**Comment by Klerith** [comment]
Probably this is a little too late, but you can achieve that using the animate property as you said.
```
FadeOutLeft(child: const Square(), animate: _animate, ),
FadeOutUp(child: const Square(), animate: _animate, ),
FadeOutDown(child: const Square(), animate: _animate, ),
FadeOutRight(child: const Square(), animate: _animate, ),
```

Where _animate is a boolean that is controlled by your state (if using a stateful widget):
```
floatingActionButton: FloatingActionButton(
        child: const Icon( Icons.play_arrow_outlined ),
        onPressed: () {
          _animate = !_animate;
          print(_animate);
          setState((){});
        },
      ),
```

You can also do it using the animationController, but that is the simplest way to achieve it.
